### ISSUE TITLE
Doesn't work well with telescope

### ISSUE THREAD

**Issue by WindSoilder** [hardhackerlabs/theme-vim#1]
Hi, After trying this theme, I found it doesn't works well with telescope, please check the following recording for more details:
[![asciicast](https://asciinema.org/a/FYp4JdMkdMSnTurBghdQhUflc.svg)](https://asciinema.org/a/FYp4JdMkdMSnTurBghdQhUflc)

As you can see, the selected item's background is pink, which doesn't play well with white foreground, and matched text's fore-ground is pink too.  In `find files` box, the rightside's fore-ground color is blue, which is not readable either.
![图片](https://user-images.githubusercontent.com/22256154/233394678-4667d512-ba41-4079-a000-fc90b29df98c.png)

For more reference about telescope: https://github.com/nvim-telescope/telescope.nvim

**Comment by skoowoo** [comment]
Is it neovim?  I will fix it. thx~

**Comment by WindSoilder** [comment]
Oh, sorry for not mentioning, I'm using neovim.

**Comment by skoowoo** [comment]
I have fixed this issue, if it's okay for you, you can upgrade and check it again.

thx~

**Comment by WindSoilder** [comment]
Thank you!

It works fine for me.  You make me want to play with the theme more :-D
