### ISSUE TITLE
Doesn't work well with gitsign, indent-blankline, and language server message

### ISSUE THREAD

**Issue by WindSoilder** [hardhackerlabs/theme-vim#2]
Hi, it's me again, I found that it doesn't works well with gitsign either..please check the following recording for more details:
[![asciicast](https://asciinema.org/a/cnzjOjoYMGwOQ2yOxdLQrCM8D.svg)](https://asciinema.org/a/cnzjOjoYMGwOQ2yOxdLQrCM8D)

I think there are 3 places can be improved:
![图片](https://user-images.githubusercontent.com/22256154/233396422-b1be14d1-612d-41d9-9ab6-d1a337a282ab.png)

For more reference about gitsign: https://github.com/lewis6991/gitsigns.nvim

**Comment by skoowoo** [comment]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/834151/233576949-e53c7de6-f845-4238-af44-f472b6337e0e.png">

hi, Which plugin does the '|' sign come from ?  

gitsigns ? how to setup the plugin to show it ? sorry, i'm a fresher for it & neovim.

**Comment by WindSoilder** [comment]
Oh, sorry :-(  I'm new to vim/neovim enviornment too...I gave a wrong information.

After revisit my config file, I find it comes from indent-blankline.nvim plugin.

For more reference about ident-blankline: https://github.com/lukas-reineke/indent-blankline.nvim

**Comment by WindSoilder** [comment]
Thank you!  After trying the new version, I think it works fine for me

**Comment by WindSoilder** [comment]
> <img alt="image" width="314" src="https://user-images.githubusercontent.com/834151/233576949-e53c7de6-f845-4238-af44-f472b6337e0e.png">
> 
> hi, Which plugin does the '|' sign come from ?
> 
> gitsigns ? how to setup the plugin to show it ? sorry, i'm a fresher for it & neovim.

Hi, @skoowoo it seems that '|' sign isn't visible again..
