### ISSUE TITLE
Cannot allocate color 235

### ISSUE THREAD

**Issue by deskangel** [hardhackerlabs/theme-vim#4]
Encounter an error:

`Error detected while processing ~/.vim/bundle/hardhacker/colors/hardhacker.vim[76]..function <SNR>19_hi_group:
line   11:
E254: Cannot allocate color 235`

**Comment by skoowoo** [comment]
I feel so sorry for that. I have fixed this issue, you can try again, thx~

**Comment by skoowoo** [comment]
Fixed

**Comment by deskangel** [comment]
Confirmed! Very quick response, thanks!

Skoo Wu ***@***.***> 于 2023年4月23日周日 09:40写道：
