### ISSUE TITLE
Little improvement with `lazy.nvim` plugin

### ISSUE THREAD

**Issue by WindSoilder** [hardhackerlabs/theme-vim#5]
Hi, it's me again :-)

When I'm updating plugins with `lazy.nvim`, the relative git commit log is not really readable.

[![asciicast](https://asciinema.org/a/Y4KOztr37uJdlzlTuPtu43znk.svg)](https://asciinema.org/a/Y4KOztr37uJdlzlTuPtu43znk)

At `0:17`, you can see the following screenshot:

![图片](https://user-images.githubusercontent.com/22256154/234897485-7a2bdef9-746c-4b0d-9ee4-6095834b2a84.png)

Actually the text is not really readable(much worse than the asciinema representation itself), I think it can be improved.

For more information about lazy.nvim: https://github.com/folke/lazy.nvim

**Comment by skoowoo** [comment]
Please update, I have fixed it.
