### ISSUE TITLE
Overriding highlight groups.

### ISSUE THREAD

**Issue by jim-at-jibba** [hardhackerlabs/theme-vim#6]
Is it possible to override the highlight groups?

Anything I try seems to not work.

Thanks

**Comment by skoowoo** [comment]
How did you override the highlighting group ? 

I use the highlight command in init.lua and it works.

**Comment by jim-at-jibba** [comment]
Could you post an example as the ways I tried did not work. 

Thanks

**Comment by skoowoo** [comment]
I added this code `vim.cmd("hi Normal guifg=#ff0000 guibg=#00ff00")` to the end of init.lua file，and it changed the Normal highlight.

<img width="1544" alt="image" src="https://github.com/hardhackerlabs/theme-vim/assets/834151/21cf4a8d-2407-44c0-939b-300f6133b705">

**Comment by jim-at-jibba** [comment]
Yeah, but that effects all themes. I would want to update just the groups for this theme. I change themes regularly and have different highlight groups for each. 

Other themes give you the option to override in the set up for that theme.

Not to worry.

Thanks for your help

**Comment by skoowoo** [comment]
So, I need to export the necessary highlight groups for this theme and then you can override them.

Example:

`vim.cmd("hi HardHackerBorder guifg=#ff0000 guibg=#00ff00")`

thanks for your feedback, I will support it.

**Comment by jim-at-jibba** [comment]
Thanks for your help.

As an example, this is how I update the highlight groups for Catppucin

```lua
	{
		"catppuccin/nvim",
		lazy = true,
		name = "catppuccin",
		config = function()
			require("catppuccin").setup({
				transparent_background = true,
				custom_highlights = function(colors)
					return {
						ColorColumn = { bg = colors.pink },

						-- Blend colours against the "base" background
						CursorLine = { bg = colors.sapphire, blend = 10 },
						StatusLine = { fg = colors.flamingo, bg = colors.flamingo, blend = 10 },

						FloatBorder = { fg = colors.surface0, bg = colors.surface0 },
						NormalFloat = { bg = colors.surface0 },
						FloatTitle = { bg = colors.surface0 },

						TelescopeTitle = { fg = colors.teal, bold = true },
						TelescopePromptNormal = { bg = colors.surface0 },
						TelescopePromptBorder = { fg = colors.surface0, bg = colors.surface0 },
						TelescopeResultsNormal = { fg = colors.text, bg = colors.mantle },
						TelescopeResultsBorder = { fg = colors.mantle, bg = colors.mantle },
						TelescopePreviewNormal = { fg = colors.text, bg = colors.crust },
						TelescopePreviewBorder = { fg = colors.crust, bg = colors.crust },

						NoiceCmdLinePrompt = { fg = colors.sapphire, bold = true },
						NoiceCmdlinePopup = { fg = colors.sapphire, bg = colors.surface0 },
						NoiceCmdlinePopupBorder = { fg = colors.surface0, bg = colors.surface0 },
					}
				end,
			})
		end,
	},
```

I tried doing this but it did not work

```
	{
		"hardhackerlabs/theme-vim",
		name = "hardhacker",
		lazy = false,
		priority = 1000,
		init = function()
			vim.g.hardhacker_darker = 0
			vim.g.hardhacker_hide_tilde = 1
			vim.g.hardhacker_keyword_italic = 1
		end,
		config = function() 
                    vim.cmd("hi NoiceCmdlinePopupBorder guifg=#ff0000 guibg=#00ff00")
              end,
	},

```

Thanks again

**Comment by skoowoo** [comment]
Oh, I finally understand you，This is a good usage scenario. I also  found out the reason for the problem, I will fix it.

**Comment by jim-at-jibba** [comment]
Sorry if I was not clear.

Thanks for your time

**Comment by skoowoo** [comment]
I have provided an array that configures all custom highlights and all custom highlights will be executed at the end of the theme code.

Here is an example.
```
		config = function()
			vim.cmd("colorscheme hardhacker")

			vim.g.hardhacker_custom_highlights = {
				[[hi! link TelescopeBorder Type]],
			}
		end,
```

You can update and try it.

thx~~~~

**Comment by jim-at-jibba** [comment]
Hey,

Thanks for the speedy update. I just tried but cant seem to get it to work. Am I doing something wrong?

```
	{
		"hardhackerlabs/theme-vim",
		name = "hardhacker",
		lazy = false,
		priority = 1000,
		init = function()
			vim.g.hardhacker_darker = 0
			vim.g.hardhacker_hide_tilde = 1
			vim.g.hardhacker_keyword_italic = 1
		end,
		config = function()
			vim.g.hardhacker_custom_highlights = {
				[[hi TelescopeTitle  guifg=#ff0000 guibg=#00ff00]],
				[[hi NoiceCmdlinePopupBorder guifg=#ff0000 guibg=#00ff00]],
			}
		end,
	},

```

**Comment by skoowoo** [comment]
I use your config and it works fine. I added the `colorscheme` command in config, I don't know if related to it.


<img width="646" alt="image" src="https://github.com/hardhackerlabs/theme-vim/assets/834151/9c7e94d5-7e46-4bff-8ff9-367dca737bf9">


<img width="1152" alt="image" src="https://github.com/hardhackerlabs/theme-vim/assets/834151/a6e230f7-534f-4a2b-b9fc-fabd0fc1d9d9">

**Comment by jim-at-jibba** [comment]
Interesting.

Yeah I set the colorscheme after everything else because of a theme switching script I use. That must mess it up.

Thanks for your help.

I will close this issue if you are happy with the result. 

Thanks again
