### ISSUE TITLE
Works better with foldcolumn which provided by nvim-ufo plugin

### ISSUE THREAD

**Issue by WindSoilder** [hardhackerlabs/theme-vim#7]
Sorry, it's hard to express, please see my record:
[![asciicast](https://asciinema.org/a/EITgHrVQwMMSLzNA2HalFw6i2.svg)](https://asciinema.org/a/EITgHrVQwMMSLzNA2HalFw6i2)
As we can see, after I open a file, the `foldcolumn` at `left side` is a little hard to read.
![图片](https://github.com/hardhackerlabs/theme-vim/assets/22256154/3a736544-1ed0-44b5-8459-fd0cd320e03b)

I'm using https://github.com/kevinhwang91/nvim-ufo#minimal-configuration with `minimum-configuration` to show `foldcolumn`.

**Comment by skoowoo** [comment]
A bit ugly.

there should be no corresponding highlight group.

I will test it and fix.

thanks for feedback.

**Comment by skoowoo** [comment]
Your problem seams to be same as this: https://github.com/kevinhwang91/nvim-ufo/issues/4

please check it out.

**Comment by skoowoo** [comment]
In addition, I added the `FoldColumn` highlight group to make it better to view.

pls update theme.

thanks for your feedback.

**Comment by WindSoilder** [comment]
Thank you very much!  It looks pretty fine to me :)
![图片](https://github.com/hardhackerlabs/theme-vim/assets/22256154/b8619519-d37f-4837-b08f-801af784604b)
